apiVersion: v1
kind: Namespace
metadata:
  name: kuma-perf
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: kuma-perf
spec:
  selector:
    matchLabels:
      app: http-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: http-echo
    nodeName: kind-worker
    spec:
      containers:
        - name: http-echo
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1"
          image: "hashicorp/http-echo"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          args:
            - -listen=0.0.0.0:5000
            - -text="hello world"
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: kuma-perf
spec:
  selector:
    app: http-echo
  ports:
  - protocol: TCP
    appProtocol: http
    port: 5000
---