name: "tests"

on:
  push:
    tags: [ "v*" ]
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  CGO_ENABLED: "0"

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Set up Go"
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: "Configure go modules cache"
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: "Install dependencies"
      run: |
        go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo

    - name: "Run unit tests for iptables engine"
      run: |
        ginkgo run ./iptables/...

    - name: "Run unit tests for firewalld"
      run: |
        ginkgo run ./firewalld/...

  blackbox-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Set up Go"
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: "Configure go modules cache"
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: "Install dependencies"
      run: |
        go mod tidy
        go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo

    - name: "Run blackbox tests"
      run: |
        sudo "PATH=$PATH" $(which ginkgo) run ./test/blackbox_tests/...
